version: '3.9'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./backend/.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  mongo-data:
  elasticsearch_data:
